[package]
name = "calculator"
version = "0.0.1"
edition = "2021"
authors = ["david072"]
description = "A calculator working with text inputs."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
strum = { version = "0.24.1", features = ["derive"] }