[package]
name = "cli"
authors = ["david072"]
version = "1.0.0"
edition = "2021"

[dependencies]
calculator = { path = "../calculator" }
clap = { version = "3.2.17", features = ["derive"] }
colored = "2.0.0"
