name: Github Pages Experimental

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/pages.yml'
      - '.github/workflows/cd.yml'
      - '.github/workflows/ci.yml'
      - '.gitattributes'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'media/*'
    branches:
      - main

permissions:
  contents: write # for committing to gh-pages branch

jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # repo checkout
      - uses: actions-rs/toolchain@v1 # get rust toolchain for wasm
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      - uses: actions-ecosystem/action-get-latest-tag@v1.6.0
        id: get-latest-tag
        with:
          semver_only: true
      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: patch
      - name: Rust Cache # cache the rust build artefacts
        uses: Swatinem/rust-cache@v1
      - name: Download and install Trunk binary
        run: wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      - name: Prepare Build
        run: |
          cargo install cargo-edit -f --no-default-features -F "set-version" &&
          cd gui &&
          cargo set-version "$(echo "${{ steps.bump-semver.outputs.new_version }}" | cut -c2-)-$(git rev-parse --short HEAD)" &&
          cd assets && 
          rm sw.js && rm manifest.json &&
          mv sw_experimental.js sw.js &&
          mv manifest_experimental.json manifest.json
      - name: Build # build
        # "${GITHUB_REPOSITORY#*/}" evaluates into the name of the repository
        # using --public-url something will allow trunk to modify all the href paths like from favicon.ico to repo_name/favicon.ico .
        # this is necessary for GitHub pages where the site is deployed to username.github.io/repo_name and all files must be requested
        # relatively as eframe_template/favicon.ico. if we skip public-url option, the href paths will instead request username.github.io/favicon.ico which
        # will obviously return error 404 not found.
        run: cd gui && ../trunk build --release --public-url "${GITHUB_REPOSITORY#*/}/experimental"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: gui/dist
          branch: gh-pages
          target-folder: experimental
          # this option will not maintain any history of your previous pages deployment
          # set to false if you want all page build to be committed to your gh-pages branch history
          single-commit: true
